name = "querido-diario-workers"
main = "src/index.ts"
compatibility_date = "2024-10-01"
node_compat = true

# Dispatcher worker configuration
[env.production]
name = "querido-diario-dispatcher"

# Queue configuration
[[queues.producers]]
queue = "gazette-crawl-queue"
binding = "CRAWL_QUEUE"

[[queues.consumers]]
queue = "gazette-crawl-queue"
max_batch_size = 10
max_batch_timeout = 30
max_retries = 3
dead_letter_queue = "gazette-crawl-dlq"
script_name = "querido-diario-consumer"

# Consumer worker (separate worker for queue processing)
[env.consumer]
name = "querido-diario-consumer"
main = "src/consumer.ts"
